feat: withdrawal request queue
dashevo/rs-drive pull request #149
Opened 2022-09-14 07:09 UTC by jawid-h

## Issue being fixed or feature implemented

An attempt to use underlying grovedb to implement queue for withdrawal requests

## What was done?

- added to functions `enqueue_withdrawal` and `dequeue_withdrawals` to `Drive` implementation
- updated Node bindings
- added some tests

## How Has This Been Tested?

Unit and integration testing

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2022-09-14 09:59 UTC, QuantumExplorer requested changes

2022-09-14 09:59 UTC, QuantumExplorer commented on drive/src/drive/identity/withdrawal_queue.rs
> +    pub fn enqueue_withdrawal(
We should have a method for enqueue_withdrawals

2022-09-14 09:59 UTC, QuantumExplorer commented on drive/src/drive/identity/withdrawal_queue.rs
> +        let mut batch = GroveDbOpBatch::new();
using batches for 1 insert is not optimal.

2022-09-14 09:59 UTC, QuantumExplorer commented on drive/src/drive/identity/withdrawal_queue.rs
> +    pub fn to_cbor(&self) -> Result<Vec<u8>, Error> {
Why are we serializing withdrawals to cbor?

2022-09-14 09:59 UTC, QuantumExplorer commented on drive/src/drive/identity/withdrawal_queue.rs
> +    pub quorum_hash: Vec<u8>,
best to use a [u8, 32] here

2022-09-14 09:59 UTC, QuantumExplorer commented on drive/src/drive/identity/withdrawal_queue.rs
> +    pub quorum_sig: Vec<u8>,
best to use [u8, 96] here

2022-09-14 09:59 UTC, QuantumExplorer commented on drive/src/drive/identity/withdrawal_queue.rs
> +    pub tx_out_hash: Vec<u8>,
best to use a [u8, 32] here

2022-09-14 09:59 UTC, QuantumExplorer commented on drive/src/drive/identity/withdrawal_queue.rs
> +            .query_raw(&path_query, QueryElementResultType, transaction)
why not just query?

2022-09-14 09:59 UTC, QuantumExplorer commented on drive/src/drive/identity/withdrawal_queue.rs
> +        let withdrawals = result?;
merge this line in the previous.

2022-09-15 09:28 UTC, jawid-h commented on drive/src/drive/identity/withdrawal_queue.rs
> +    pub fn to_cbor(&self) -> Result<Vec<u8>, Error> {
@shumkov Am I missing something?

2022-09-16 13:11 UTC, shumkov requested changes
Discussed verbaly

2022-09-21 16:37 UTC, shumkov requested changes

2022-09-21 16:37 UTC, shumkov commented on dash-abci/src/abci/handlers.rs
> +        let withdrawal_transactions = self.drive.dequeue_withdrawals(transaction)?;
`self.drive.dequeue_withdrawal_transactions`

2022-09-21 16:37 UTC, shumkov commented on dash-abci/src/abci/handlers.rs
> +        let withdrawal_bytes = withdrawal_transactions
// Append request_height and quorum_hash to withdrwal transaction and pass it to JS Drive for singing and broadcasting

2022-09-21 16:37 UTC, shumkov commented on dash-abci/src/abci/messages.rs
> +    pub quorum_hash: [u8; 32],
validator_set_quorum_hash

2022-09-21 16:37 UTC, shumkov commented on dash-abci/src/abci/messages.rs
> +    pub withdrawal_transactions: Vec<Vec<u8>>,
raw_withdrawal_transactions to point that thet are incomplete

2022-09-21 16:37 UTC, shumkov commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/apply_identity_credit_withdrawal_transition_factory.rs
> +        self.state_repository
Let's add a todo that we need to be able batch state repository operations

2022-09-21 16:37 UTC, shumkov commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/apply_identity_credit_withdrawal_transition_factory.rs
> +        let tx_out =
We should create an output from `output_script`.

2022-09-21 16:37 UTC, shumkov commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/mod.rs
>      pub output: Vec<u8>,
output_script

2022-09-22 13:14 UTC, shumkov requested changes

2022-09-22 13:14 UTC, shumkov commented on dash-abci/src/abci/handlers.rs
> +        let withdrawal_transactions = self.drive.dequeue_withdrawal_transactions(transaction)?;
I would pass count. It seems more like execution responsibility rather than queue

2022-09-22 13:14 UTC, shumkov commented on dash-abci/src/abci/handlers.rs
> +            raw_withdrawal_transactions: withdrawal_transaction_bytes,
unsigned_withdrawal_transactions

2022-09-22 13:14 UTC, shumkov commented on dash-abci/src/abci/handlers.rs
> +        let withdrawal_transaction_bytes = withdrawal_transactions
unsigned_withdrawal_transactions_bytes

2022-09-22 13:14 UTC, shumkov commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/apply_identity_credit_withdrawal_transition_factory.rs
> +        let output_script = Script(state_transition.output_script.into_boxed_slice());
state_transition.output_script should be already Script

2022-09-22 13:14 UTC, shumkov commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/apply_identity_credit_withdrawal_transition_factory.rs
> +            value: state_transition.amount,
`amount` should be in credits. Here you are passing duffss. Please use a convert function

2022-09-22 13:14 UTC, shumkov commented on drive/src/drive/identity/withdrawal_queue.rs
> +        let mut batch = GroveDbOpBatch::new();
Yes, we need to pass batch from outside, since we will use one single batch for the whole apply state transition logic

2022-09-22 13:14 UTC, shumkov commented on drive/src/drive/identity/withdrawal_queue.rs
> +        self.apply_batch_grovedb_operations(true, transaction, batch, &mut drive_operations)?;
We should move this up too

2022-09-22 13:14 UTC, shumkov commented on drive/src/drive/identity/withdrawal_queue.rs
> +    pub fn enqueue_withdrawal_transactions(
add_enqueue_withdrawal_transaction_operations

2022-09-22 13:14 UTC, shumkov commented on drive/src/drive/mod.rs
> +            RootTree::Withdrawals => &[5],
WithdrawalTransactions

2022-09-22 13:14 UTC, shumkov commented on drive/src/error/identity.rs
> +pub enum WithdrawalError {
You don't use it

2022-09-22 13:14 UTC, shumkov commented on node/Drive.js
> +  }
We don't need this

2022-09-22 13:14 UTC, shumkov commented on node/Drive.js
> +          quorumHash: Array.from(request.quorumHash),
validatorSetQuorumHash

2022-09-22 13:14 UTC, shumkov commented on node/src/lib.rs
> +    fn js_enqueue_withdrawals(mut cx: FunctionContext) -> JsResult<JsUndefined> {
We don't need those two

2022-10-03 14:58 UTC, shumkov requested changes
we need to implement validation for coreFee and outputScript

2022-10-03 14:58 UTC, shumkov commented on dash-abci/src/abci/handlers.rs
We need test new logic

2022-10-04 17:39 UTC, shumkov requested changes

2022-10-04 17:39 UTC, shumkov commented on dpp/src/errors/codes.rs
>              Self::IdentityInsufficientBalanceError(_) => 4023,
This one is busy in js dpp

2022-10-04 17:39 UTC, shumkov commented on dpp/src/identity/script.rs
> +impl Script {
CoreScript?

2022-10-04 17:39 UTC, shumkov commented on dpp/src/identity/script.rs
> +    pub fn is_p2sh(&self) -> bool {
Shall we implement Deref pattern so all Script methods will "accessible" with CoreScript as well?

2022-10-04 17:39 UTC, shumkov commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/validation/basic/validate_identity_credit_withdrawal_transition_basic.rs
> +        let identity_credit_withdrawal_transition_map =
If we can't parse it must be consensus error. @antouhou what do you think?

2022-10-04 17:39 UTC, shumkov commented on dpp/src/schema/identity/stateTransition/identityCreditWithdrawal.json
>        "minItems": 10,
p2sh for 23, and 25 for p2pkh so let's do from 23 to 25 inclusive

2022-10-04 17:39 UTC, shumkov commented on drive/src/drive/initialization.rs
> +        batch.add_insert_empty_tree(vec![], vec![RootTree::WithdrawalTransactions as u8]);
5th is already busy for Misc tree (please add it here too)

2022-10-13 16:33 UTC, shumkov commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/validation/basic/validate_identity_credit_withdrawal_transition_basic.rs
> +        let identity_credit_withdrawal_transition_map =
Agreed to deal with it in another PR

2022-10-13 16:40 UTC, shumkov requested changes

2022-10-13 16:40 UTC, shumkov commented on drive/src/drive/initialization.rs
> +        batch.add_insert_empty_tree(vec![], vec![RootTree::WithdrawalTransactionsCounter as u8]);
I wouldn't create an additional tree on root level just for counter. Let's have one for withdrawals which have two leaves: queue and counter.

2022-10-17 09:49 UTC, shumkov requested changes

2022-10-17 09:49 UTC, shumkov commented on dpp/Cargo.toml
> +dashcore = { git="https://github.com/dashevo/rust-dashcore", features=["no-std", "secp-recovery", "rand", "signer"], default-features = false, rev="71573a414126de0e0239bb9ecf2d0e0164d4165e" }
Let's switch to master?

2022-10-17 09:49 UTC, shumkov commented on drive/src/drive/initialization.rs
> +        );
I would move it to a separate function in withdrawal module

2022-10-17 12:39 UTC, QuantumExplorer requested changes

2022-10-17 12:39 UTC, QuantumExplorer commented on dash-abci/src/abci/handlers.rs
> +            .collect::<Result<Vec<Vec<u8>>, Error>>()?;
I believe this should be it's own function. We want to keep things in block begin very structured.

2022-10-17 12:39 UTC, QuantumExplorer commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/apply_identity_credit_withdrawal_transition_factory.rs
> +        let output_script: Script = (*state_transition.output_script).clone();
Better do state_transition.output_script.deref().clone();

2022-10-17 12:39 UTC, QuantumExplorer commented on dpp/src/identity/state_transition/identity_credit_withdrawal_transition/apply_identity_credit_withdrawal_transition_factory.rs
> +        let withdrwal_transaction = AssetUnlockBaseTransactionInfo {
withdrawal is misspelled

2022-10-17 12:39 UTC, QuantumExplorer commented on dpp/src/tests/identity/state_transition/identity_credit_withdrawal_transition/apply_identity_credit_withdrawal_transition_factory_spec.rs
> +            .returning(|| anyhow::Ok(42));
why 42?

2022-10-17 12:39 UTC, QuantumExplorer commented on dpp/src/tests/identity/state_transition/identity_credit_withdrawal_transition/identity_credit_withdrawal_transition_spec.rs
> +            *state_transition.output_script,
deref is better here

2022-10-17 15:18 UTC, shumkov approved these changes
LGTM! 👍

2022-10-17 15:41 UTC, QuantumExplorer approved these changes

2022-10-17 16:26 UTC, merged