fix: query empty contract fails
dashevo/rs-drive pull request #65
Opened 2022-02-16 16:23 UTC by shumkov

2022-02-16 16:25 UTC, jawid-h approved these changes, later dismissed
lgtmt

2022-02-16 19:50 UTC, QuantumExplorer requested changes
This does not work as InvalidPath can give back many string messages, some that are for a valid query, some that are not.

2022-02-16 20:13 UTC, QuantumExplorer commented
Dependent on https://github.com/dashevo/grovedb/pull/72

2022-02-16 20:13 UTC, QuantumExplorer approved these changes, later dismissed

2022-02-17 04:53 UTC, QuantumExplorer approved these changes

2022-02-17 04:58 UTC, merged